//! This example is a playground for calculating things about the Zeckendorf Spiral.
//!
//! Zeckendorf Spiral is a spiral that is generated by the Zeckendorf representation of the Fibonacci numbers.
//!
//! See https://zeckendorf.lovable.app/ for a demonstration of the spiral.
//! Source code: https://github.com/pRizz/zeckendorf-spiral
//!
//! Run with: `cargo run --release --example spiral`

use std::time::Instant;
// TODO: try using f128 for better precision; f128 is only available on nightly though; need to use a different library.

use num_bigint::BigUint;
use zeck::*;

mod shared;
use shared::*;

fn main() {
    let start_time = Instant::now();

    sum_the_areas_in_the_gap_of_the_spiral_f64();

    let end_time = Instant::now();
    println!("Time taken: {:?}", end_time.duration_since(start_time));
}

fn get_gap_area_at_index_f64(index: u64) -> f64 {
    let f_2n_arc = memoized_fast_doubling_fibonacci_biguint(2 * index);
    let f_2n_plus_2_arc = memoized_fast_doubling_fibonacci_biguint(2 * index + 2);
    let f_2n_plus_4_arc = memoized_fast_doubling_fibonacci_biguint(2 * index + 4);
    // Take a reference outside the Arc to make operations on these values easier, and the original value still lives in the Arc.
    let f_2n = f_2n_arc.as_ref();
    let f_2n_plus_2 = f_2n_plus_2_arc.as_ref();
    let f_2n_plus_4 = f_2n_plus_4_arc.as_ref();

    sqrt(f_2n_plus_2 * f_2n_plus_4)
        - biguint_to_approximate_f64(f_2n_plus_2)
        - sqrt(f_2n_plus_2 * f_2n)
}

/// The sum of the gaps in the Zeckendorf Spiral is 1!
/// This proves that an infinite sum of irrational numbers can be a rational number.
/// Essentially,
fn sum_the_areas_in_the_gap_of_the_spiral_f64() {
    let start_time = Instant::now();

    let mut total_gap_area = 0.0;
    let mut prev_gap_area = 0.0;
    let mut prev_ratio_of_consecutive_gap_areas = 0.0;
    for index in 0..1000 {
        let gap_area = get_gap_area_at_index_f64(index);
        println!("index: {index}, gap_area: {}", gap_area);
        if prev_gap_area != 0.0 {
            let ratio_of_consecutive_gap_areas = gap_area / prev_gap_area;
            // Seems to converge to 1/(φ^2) or ≈ 0.38196601125
            println!(
                "index: {index}, ratio_of_consecutive_gap_areas: {}",
                ratio_of_consecutive_gap_areas
            );
            if prev_ratio_of_consecutive_gap_areas != 0.0 {
                let ratio_of_consecutive_ratio_of_consecutive_gap_areas =
                    ratio_of_consecutive_gap_areas / prev_ratio_of_consecutive_gap_areas;
                println!(
                    "index: {index}, ratio_of_consecutive_ratio_of_consecutive_gap_areas: {}",
                    ratio_of_consecutive_ratio_of_consecutive_gap_areas
                );
            }
            prev_ratio_of_consecutive_gap_areas = ratio_of_consecutive_gap_areas;
        }
        prev_gap_area = gap_area;
        if gap_area < f64::MIN_POSITIVE {
            println!("gap_area converged to 0 at index {index}");
            break;
        }
        total_gap_area += gap_area;
    }
    println!("total_gap_area: {}", total_gap_area);

    let end_time = Instant::now();
    println!("Time taken: {:?}", end_time.duration_since(start_time));
}

/// The purpose of this trait is to allow functions to be able to take either
/// BigUints or refs of BigUints.
trait AsBigUintRef {
    fn as_biguint_ref(&self) -> &BigUint;
}

impl AsBigUintRef for BigUint {
    fn as_biguint_ref(&self) -> &BigUint {
        self
    }
}

impl AsBigUintRef for &BigUint {
    fn as_biguint_ref(&self) -> &BigUint {
        self
    }
}

fn sqrt<T: AsBigUintRef>(x: T) -> f64 {
    biguint_to_approximate_f64(x.as_biguint_ref()).sqrt()
}
